import { Cargo } from '../cargo/types';
import { RAIL_SPECS } from './railCatalog';
import { AIRCRAFT_SPECS, SHIP_SPECS } from './waterCatalog';
import { kmh, RailRole, VehicleKind, type VehicleSpec } from './spec';

/**
 * Vehicle catalogue - pure data (section 11.5).
 *
 * The road table lives here, the rail table in ./railCatalog.ts; both use the
 * shape defined in ./spec.ts, and this file is where they are joined into the
 * one list everything else looks things up in. Water and air follow with their
 * milestones the same way.
 *
 * All names are invented type designations. No real manufacturer, series or
 * model name appears anywhere in this project; that is a legal requirement, not
 * a stylistic one.
 */

export { RailRole, VehicleKind } from './spec';
export type { PowerSource, VehicleSpec } from './spec';

const ROAD_SPECS: readonly VehicleSpec[] = [
  // ------------------------------------------------------------ buses
  {
    id: 200,
    nameKey: 'veh.bus_o1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1968,
    priceCt: 550_000,
    upkeepCtPerYear: 45_000,
    massKg: 9_000,
    lengthM: 9,
    tractiveN: 14_000,
    powerW: 85_000,
    maxSpeedMs: kmh(62),
    capacity: { [Cargo.CommuterPax]: 150 },
    refittable: [Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_300,
    lifetimeYears: 16,
    co2PerKm: 0.95,
  },
  {
    id: 201,
    nameKey: 'veh.bus_o2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1962,
    retireYear: 1984,
    priceCt: 1_300_000,
    upkeepCtPerYear: 76_000,
    massKg: 11_500,
    lengthM: 11,
    tractiveN: 19_000,
    powerW: 125_000,
    maxSpeedMs: kmh(78),
    capacity: { [Cargo.CommuterPax]: 200 },
    refittable: [Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_700,
    lifetimeYears: 18,
    co2PerKm: 1.05,
  },
  {
    id: 202,
    nameKey: 'veh.bus_o3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1979,
    retireYear: 2001,
    priceCt: 1_820_000,
    upkeepCtPerYear: 90_000,
    massKg: 13_000,
    lengthM: 12,
    tractiveN: 23_000,
    powerW: 165_000,
    maxSpeedMs: kmh(90),
    capacity: { [Cargo.CommuterPax]: 260 },
    refittable: [Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_000,
    lifetimeYears: 20,
    co2PerKm: 1.1,
  },
  {
    id: 203,
    nameKey: 'veh.bus_articulated',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1994,
    retireYear: 2024,
    priceCt: 2_760_000,
    upkeepCtPerYear: 122_000,
    massKg: 19_000,
    lengthM: 18,
    tractiveN: 31_000,
    powerW: 240_000,
    maxSpeedMs: kmh(85),
    capacity: { [Cargo.CommuterPax]: 420 },
    refittable: [Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_200,
    lifetimeYears: 22,
    co2PerKm: 1.4,
  },
  {
    id: 204,
    nameKey: 'veh.bus_hybrid',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2012,
    retireYear: 2038,
    priceCt: 3_360_000,
    upkeepCtPerYear: 108_000,
    massKg: 18_000,
    lengthM: 12,
    tractiveN: 34_000,
    powerW: 210_000,
    maxSpeedMs: kmh(92),
    capacity: { [Cargo.CommuterPax]: 320 },
    refittable: [Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 20,
    co2PerKm: 0.62,
  },
  {
    id: 205,
    nameKey: 'veh.bus_battery',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2026,
    retireYear: 2050,
    priceCt: 4_200_000,
    upkeepCtPerYear: 80_000,
    massKg: 20_000,
    lengthM: 12,
    tractiveN: 40_000,
    powerW: 260_000,
    maxSpeedMs: kmh(95),
    capacity: { [Cargo.CommuterPax]: 360 },
    refittable: [Cargo.BusinessPax],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_600,
    lifetimeYears: 22,
    co2PerKm: 0.08,
  },
  {
    id: 206,
    nameKey: 'veh.bus_double',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2035,
    retireYear: 2050,
    priceCt: 5_280_000,
    upkeepCtPerYear: 112_000,
    massKg: 24_000,
    lengthM: 14,
    tractiveN: 46_000,
    powerW: 320_000,
    maxSpeedMs: kmh(100),
    capacity: { [Cargo.CommuterPax]: 520 },
    refittable: [Cargo.BusinessPax],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_700,
    lifetimeYears: 24,
    co2PerKm: 0.1,
  },

  // ------------------------------------------------------------- mail
  {
    id: 220,
    nameKey: 'veh.mail_van1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1975,
    priceCt: 2_900_000,
    upkeepCtPerYear: 127_000,
    massKg: 5_500,
    lengthM: 6,
    tractiveN: 9_000,
    powerW: 60_000,
    maxSpeedMs: kmh(68),
    capacity: { [Cargo.Mail]: 44 },
    refittable: [Cargo.CommuterPax, Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_400,
    lifetimeYears: 15,
    co2PerKm: 0.7,
  },
  {
    id: 221,
    nameKey: 'veh.mail_van2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1972,
    retireYear: 2004,
    priceCt: 4_600_000,
    upkeepCtPerYear: 153_000,
    massKg: 7_200,
    lengthM: 7,
    tractiveN: 13_000,
    powerW: 95_000,
    maxSpeedMs: kmh(88),
    capacity: { [Cargo.Mail]: 76 },
    refittable: [Cargo.CommuterPax, Cargo.BusinessPax],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_900,
    lifetimeYears: 18,
    co2PerKm: 0.8,
  },
  {
    id: 222,
    nameKey: 'veh.mail_van3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2001,
    retireYear: 2050,
    priceCt: 7_800_000,
    upkeepCtPerYear: 173_000,
    massKg: 8_500,
    lengthM: 8,
    tractiveN: 18_000,
    powerW: 140_000,
    maxSpeedMs: kmh(100),
    capacity: { [Cargo.Mail]: 110 },
    refittable: [Cargo.CommuterPax, Cargo.BusinessPax],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 20,
    co2PerKm: 0.12,
  },

  // ----------------------------------------------------------- lorries
  {
    id: 240,
    nameKey: 'veh.lorry_bulk1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1974,
    priceCt: 4_200_000,
    upkeepCtPerYear: 173_000,
    massKg: 12_000,
    lengthM: 8,
    tractiveN: 22_000,
    powerW: 105_000,
    maxSpeedMs: kmh(55),
    capacity: { [Cargo.Coal]: 28 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_200,
    lifetimeYears: 16,
    co2PerKm: 1.3,
  },
  {
    id: 241,
    nameKey: 'veh.lorry_bulk2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1971,
    retireYear: 1998,
    priceCt: 6_900_000,
    upkeepCtPerYear: 220_000,
    massKg: 17_000,
    lengthM: 10,
    tractiveN: 32_000,
    powerW: 170_000,
    maxSpeedMs: kmh(72),
    capacity: { [Cargo.Coal]: 44 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood, Cargo.Cement],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_800,
    lifetimeYears: 18,
    co2PerKm: 1.6,
  },
  {
    id: 242,
    nameKey: 'veh.lorry_bulk3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1995,
    retireYear: 2028,
    priceCt: 10_400_000,
    upkeepCtPerYear: 260_000,
    massKg: 21_000,
    lengthM: 12,
    tractiveN: 44_000,
    powerW: 260_000,
    maxSpeedMs: kmh(88),
    capacity: { [Cargo.Coal]: 64 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood, Cargo.Cement],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_200,
    lifetimeYears: 20,
    co2PerKm: 1.75,
  },
  {
    id: 243,
    nameKey: 'veh.lorry_bulk4',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2024,
    retireYear: 2050,
    priceCt: 15_800_000,
    upkeepCtPerYear: 207_000,
    massKg: 24_000,
    lengthM: 12,
    tractiveN: 52_000,
    powerW: 320_000,
    maxSpeedMs: kmh(95),
    capacity: { [Cargo.Coal]: 80 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood, Cargo.Cement],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_600,
    lifetimeYears: 22,
    co2PerKm: 0.14,
  },
  {
    id: 250,
    nameKey: 'veh.lorry_box1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1953,
    retireYear: 1980,
    priceCt: 4_800_000,
    upkeepCtPerYear: 180_000,
    massKg: 12_500,
    lengthM: 9,
    tractiveN: 23_000,
    powerW: 110_000,
    maxSpeedMs: kmh(62),
    capacity: { [Cargo.Goods]: 24 },
    refittable: [Cargo.Goods, Cargo.Planks, Cargo.Steel, Cargo.Plastics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_300,
    lifetimeYears: 16,
    co2PerKm: 1.25,
  },
  {
    id: 251,
    nameKey: 'veh.lorry_box2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1977,
    retireYear: 2006,
    priceCt: 7_900_000,
    upkeepCtPerYear: 233_000,
    massKg: 18_000,
    lengthM: 11,
    tractiveN: 35_000,
    powerW: 185_000,
    maxSpeedMs: kmh(80),
    capacity: { [Cargo.Goods]: 40 },
    refittable: [Cargo.Goods, Cargo.Planks, Cargo.Steel, Cargo.Plastics, Cargo.Electronics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_900,
    lifetimeYears: 18,
    co2PerKm: 1.5,
  },
  {
    id: 252,
    nameKey: 'veh.lorry_box3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2003,
    retireYear: 2040,
    priceCt: 12_200_000,
    upkeepCtPerYear: 270_000,
    massKg: 22_000,
    lengthM: 13,
    tractiveN: 46_000,
    powerW: 270_000,
    maxSpeedMs: kmh(92),
    capacity: { [Cargo.Goods]: 60 },
    refittable: [Cargo.Goods, Cargo.Planks, Cargo.Steel, Cargo.Plastics, Cargo.Electronics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_300,
    lifetimeYears: 20,
    co2PerKm: 1.6,
  },
  {
    id: 260,
    nameKey: 'veh.lorry_reefer1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1958,
    retireYear: 1990,
    priceCt: 6_100_000,
    upkeepCtPerYear: 230_000,
    massKg: 14_000,
    lengthM: 10,
    tractiveN: 25_000,
    powerW: 125_000,
    maxSpeedMs: kmh(66),
    capacity: { [Cargo.Food]: 24 },
    refittable: [Cargo.Food, Cargo.Livestock, Cargo.Chemicals],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 8_400,
    lifetimeYears: 16,
    co2PerKm: 1.45,
  },
  {
    id: 261,
    nameKey: 'veh.lorry_reefer2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1988,
    retireYear: 2022,
    priceCt: 10_800_000,
    upkeepCtPerYear: 293_000,
    massKg: 19_500,
    lengthM: 12,
    tractiveN: 40_000,
    powerW: 230_000,
    maxSpeedMs: kmh(86),
    capacity: { [Cargo.Food]: 44 },
    refittable: [Cargo.Food, Cargo.Livestock, Cargo.Chemicals],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 9_100,
    lifetimeYears: 19,
    co2PerKm: 1.7,
  },
  {
    id: 262,
    nameKey: 'veh.lorry_reefer3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2020,
    retireYear: 2050,
    priceCt: 16_400_000,
    upkeepCtPerYear: 240_000,
    massKg: 23_000,
    lengthM: 13,
    tractiveN: 50_000,
    powerW: 300_000,
    maxSpeedMs: kmh(95),
    capacity: { [Cargo.Food]: 60 },
    refittable: [Cargo.Food, Cargo.Livestock, Cargo.Chemicals],
    power: 'hydrogen',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 9_500,
    lifetimeYears: 21,
    co2PerKm: 0.2,
  },
  {
    id: 270,
    nameKey: 'veh.tanker1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1955,
    retireYear: 1986,
    priceCt: 5_600_000,
    upkeepCtPerYear: 213_000,
    massKg: 15_000,
    lengthM: 10,
    tractiveN: 27_000,
    powerW: 130_000,
    maxSpeedMs: kmh(58),
    capacity: { [Cargo.Oil]: 32 },
    refittable: [Cargo.Oil, Cargo.Chemicals],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_200,
    lifetimeYears: 17,
    co2PerKm: 1.4,
  },
  {
    id: 271,
    nameKey: 'veh.tanker2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1984,
    retireYear: 2018,
    priceCt: 9_400_000,
    upkeepCtPerYear: 263_000,
    massKg: 20_000,
    lengthM: 12,
    tractiveN: 42_000,
    powerW: 240_000,
    maxSpeedMs: kmh(80),
    capacity: { [Cargo.Oil]: 52 },
    refittable: [Cargo.Oil, Cargo.Chemicals],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_000,
    lifetimeYears: 19,
    co2PerKm: 1.65,
  },
  {
    id: 272,
    nameKey: 'veh.tanker3',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 2016,
    retireYear: 2050,
    priceCt: 14_600_000,
    upkeepCtPerYear: 233_000,
    massKg: 23_500,
    lengthM: 13,
    tractiveN: 50_000,
    powerW: 300_000,
    maxSpeedMs: kmh(90),
    capacity: { [Cargo.Oil]: 68 },
    refittable: [Cargo.Oil, Cargo.Chemicals],
    power: 'hydrogen',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 21,
    co2PerKm: 0.22,
  },
  {
    id: 280,
    nameKey: 'veh.lorry_container1',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1968,
    retireYear: 2000,
    priceCt: 8_200_000,
    upkeepCtPerYear: 243_000,
    massKg: 18_000,
    lengthM: 13,
    tractiveN: 36_000,
    powerW: 190_000,
    maxSpeedMs: kmh(78),
    capacity: { [Cargo.Containers]: 4 },
    refittable: [Cargo.Containers, Cargo.Goods],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_700,
    lifetimeYears: 18,
    co2PerKm: 1.55,
  },
  {
    id: 281,
    nameKey: 'veh.lorry_container2',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1998,
    retireYear: 2050,
    priceCt: 13_100_000,
    upkeepCtPerYear: 283_000,
    massKg: 24_000,
    lengthM: 15,
    tractiveN: 48_000,
    powerW: 290_000,
    maxSpeedMs: kmh(90),
    capacity: { [Cargo.Containers]: 6 },
    refittable: [Cargo.Containers, Cargo.Goods],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_300,
    lifetimeYears: 20,
    co2PerKm: 1.7,
  },
  {
    id: 290,
    nameKey: 'veh.lorry_livestock',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1951,
    retireYear: 1992,
    priceCt: 4_900_000,
    upkeepCtPerYear: 187_000,
    massKg: 13_000,
    lengthM: 10,
    tractiveN: 24_000,
    powerW: 115_000,
    maxSpeedMs: kmh(60),
    capacity: { [Cargo.Livestock]: 36 },
    refittable: [Cargo.Livestock, Cargo.Grain],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_300,
    lifetimeYears: 16,
    co2PerKm: 1.3,
  },
  {
    id: 291,
    nameKey: 'veh.lorry_cement',
    kind: VehicleKind.Road,
    railRole: RailRole.None,
    introYear: 1966,
    retireYear: 2010,
    priceCt: 6_400_000,
    upkeepCtPerYear: 227_000,
    massKg: 17_500,
    lengthM: 11,
    tractiveN: 34_000,
    powerW: 180_000,
    maxSpeedMs: kmh(70),
    capacity: { [Cargo.Cement]: 40 },
    refittable: [Cargo.Cement, Cargo.Gravel],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_800,
    lifetimeYears: 18,
    co2PerKm: 1.5,
  },
];

/** Every buildable vehicle of every mode, in one list. */
export const VEHICLE_SPECS: readonly VehicleSpec[] = [
  ...ROAD_SPECS,
  ...RAIL_SPECS,
  ...SHIP_SPECS,
  ...AIRCRAFT_SPECS,
];

const SPEC_BY_ID = new Map<number, VehicleSpec>(VEHICLE_SPECS.map((spec) => [spec.id, spec]));

export function vehicleSpec(id: number): VehicleSpec {
  const spec = SPEC_BY_ID.get(id);
  if (spec === undefined) throw new Error(`Unknown vehicle spec ${id}`);
  return spec;
}

export function hasVehicleSpec(id: number): boolean {
  return SPEC_BY_ID.has(id);
}

/**
 * Vehicles of a kind that can be bought in `year`, in catalogue order.
 * Sorted by id so the list is stable regardless of how the table is edited.
 */
export function availableVehicles(kind: VehicleKind, year: number): VehicleSpec[] {
  const result: VehicleSpec[] = [];
  for (const spec of VEHICLE_SPECS) {
    if (spec.kind !== kind) continue;
    if (year < spec.introYear || year > spec.retireYear) continue;
    result.push(spec);
  }
  result.sort((a, b) => a.id - b.id);
  return result;
}

/** Rail vehicles of one role that can be bought in `year`. */
export function availableRailVehicles(role: RailRole, year: number): VehicleSpec[] {
  const result: VehicleSpec[] = [];
  for (const spec of VEHICLE_SPECS) {
    if (spec.railRole !== role) continue;
    if (year < spec.introYear || year > spec.retireYear) continue;
    result.push(spec);
  }
  result.sort((a, b) => a.id - b.id);
  return result;
}

/** The cargo a vehicle carries by default: the first entry of its capacity. */
export function defaultCargo(spec: VehicleSpec): Cargo {
  const keys = Object.keys(spec.capacity);
  return Number(keys[0] ?? 0) as Cargo;
}

/** Capacity for a cargo type, taking a refit into account. */
export function capacityFor(spec: VehicleSpec, cargo: Cargo): number {
  const direct = spec.capacity[cargo];
  if (direct !== undefined) return direct;
  if (!spec.refittable.includes(cargo)) return 0;
  // A refitted vehicle carries what its original load would have been.
  const base = spec.capacity[defaultCargo(spec)] ?? 0;
  return base;
}
