import { Cargo } from '../cargo/types';
import { kmh, RailRole, VehicleKind, type VehicleSpec } from './spec';

/**
 * Ships and aircraft (section 11.5): twelve of each, 1950 to 2050.
 *
 * All names are invented type designations. No real shipyard, airline,
 * manufacturer or series appears anywhere - that is a legal requirement of the
 * brief, not a stylistic one.
 *
 * What makes these two modes different from road and rail, and what the numbers
 * have to express:
 *
 *  - a SHIP is slow and enormous. It carries five to twenty times what a train
 *    carries and moves at a third of the speed, so it only pays over distance -
 *    which is exactly the niche the acceptance case of M7 puts it in.
 *  - an AIRCRAFT is the opposite: small, extremely fast and expensive to keep.
 *    It pays for passengers and mail across the map and never for coal.
 *
 * The aircraft capacities are NOT real seat counts. This game's passenger unit
 * is plainly not one person - a 1950 bus carries a hundred and fifty of them -
 * and the first draft, written as real seat counts, produced three airliners
 * whose ceiling revenue was below their own upkeep. The tariff diagnostic
 * caught it; the figures are scaled to the unit the rest of the catalogue uses
 * (DECISIONS.md D-096).
 *
 * `tractiveN` and `powerW` are read by the longitudinal solver of section 11.1
 * exactly as they are for a train. A ship's drag coefficient is 40 against a
 * train's 5.5, which is what makes a ship take so long to reach its speed and
 * so long to lose it.
 */

export const SHIP_SPECS: readonly VehicleSpec[] = [
  // ------------------------------------------------------------ coasters
  {
    id: 2000,
    nameKey: 'veh.ship_coaster1',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1978,
    priceCt: 12_000_000,
    upkeepCtPerYear: 640_000,
    massKg: 900_000,
    lengthM: 55,
    tractiveN: 140_000,
    powerW: 900_000,
    maxSpeedMs: kmh(22),
    capacity: { [Cargo.Coal]: 400 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood, Cargo.Cement],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_600,
    lifetimeYears: 30,
    co2PerKm: 22,
  },
  {
    id: 2001,
    nameKey: 'veh.ship_coaster2',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1972,
    retireYear: 2010,
    priceCt: 19_500_000,
    upkeepCtPerYear: 880_000,
    massKg: 1_600_000,
    lengthM: 78,
    tractiveN: 210_000,
    powerW: 1_650_000,
    maxSpeedMs: kmh(28),
    capacity: { [Cargo.Coal]: 700 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Wood, Cargo.Cement],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_900,
    lifetimeYears: 32,
    co2PerKm: 31,
  },
  {
    id: 2002,
    nameKey: 'veh.ship_bulker',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1995,
    retireYear: 2050,
    priceCt: 34_000_000,
    upkeepCtPerYear: 1_320_000,
    massKg: 3_200_000,
    lengthM: 120,
    tractiveN: 320_000,
    powerW: 3_100_000,
    maxSpeedMs: kmh(31),
    capacity: { [Cargo.Coal]: 1_400 },
    refittable: [Cargo.Coal, Cargo.IronOre, Cargo.Gravel, Cargo.Grain, Cargo.Cement],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_200,
    lifetimeYears: 34,
    co2PerKm: 48,
  },
  // ------------------------------------------------------------ tankers
  {
    id: 2010,
    nameKey: 'veh.ship_tanker1',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1985,
    priceCt: 15_500_000,
    upkeepCtPerYear: 760_000,
    massKg: 1_200_000,
    lengthM: 68,
    tractiveN: 160_000,
    powerW: 1_100_000,
    maxSpeedMs: kmh(21),
    capacity: { [Cargo.Oil]: 480 },
    refittable: [Cargo.Oil, Cargo.Chemicals],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_500,
    lifetimeYears: 29,
    co2PerKm: 26,
  },
  {
    id: 2011,
    nameKey: 'veh.ship_tanker2',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1980,
    retireYear: 2035,
    priceCt: 28_000_000,
    upkeepCtPerYear: 1_180_000,
    massKg: 2_600_000,
    lengthM: 104,
    tractiveN: 260_000,
    powerW: 2_400_000,
    maxSpeedMs: kmh(27),
    capacity: { [Cargo.Oil]: 1_100 },
    refittable: [Cargo.Oil, Cargo.Chemicals, Cargo.Plastics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_000,
    lifetimeYears: 33,
    co2PerKm: 41,
  },
  // ------------------------------------------------------- container ships
  {
    id: 2020,
    nameKey: 'veh.ship_container1',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1968,
    retireYear: 2005,
    priceCt: 26_000_000,
    upkeepCtPerYear: 1_150_000,
    massKg: 2_100_000,
    lengthM: 96,
    tractiveN: 240_000,
    powerW: 2_200_000,
    maxSpeedMs: kmh(33),
    capacity: { [Cargo.Containers]: 320 },
    refittable: [Cargo.Containers, Cargo.Goods, Cargo.Electronics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_000,
    lifetimeYears: 31,
    co2PerKm: 38,
  },
  {
    id: 2021,
    nameKey: 'veh.ship_container2',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 2000,
    retireYear: 2050,
    priceCt: 48_000_000,
    upkeepCtPerYear: 1_750_000,
    massKg: 4_400_000,
    lengthM: 155,
    tractiveN: 380_000,
    powerW: 4_600_000,
    maxSpeedMs: kmh(38),
    capacity: { [Cargo.Containers]: 780 },
    refittable: [Cargo.Containers, Cargo.Goods, Cargo.Electronics],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 35,
    co2PerKm: 57,
  },
  {
    id: 2022,
    nameKey: 'veh.ship_container3',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 2030,
    retireYear: 2050,
    priceCt: 62_000_000,
    upkeepCtPerYear: 1_450_000,
    massKg: 4_800_000,
    lengthM: 168,
    tractiveN: 400_000,
    powerW: 5_200_000,
    maxSpeedMs: kmh(40),
    capacity: { [Cargo.Containers]: 900 },
    refittable: [Cargo.Containers, Cargo.Goods, Cargo.Electronics],
    power: 'hydrogen',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_500,
    lifetimeYears: 35,
    co2PerKm: 4,
  },
  // ------------------------------------------------------------ reefers
  {
    id: 2030,
    nameKey: 'veh.ship_reefer',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1962,
    retireYear: 2020,
    priceCt: 22_000_000,
    upkeepCtPerYear: 1_050_000,
    massKg: 1_500_000,
    lengthM: 84,
    tractiveN: 200_000,
    powerW: 1_800_000,
    maxSpeedMs: kmh(30),
    capacity: { [Cargo.Food]: 520 },
    refittable: [Cargo.Food, Cargo.Livestock, Cargo.Grain],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 8_800,
    lifetimeYears: 30,
    co2PerKm: 34,
  },
  // ------------------------------------------------------------- ferries
  {
    id: 2040,
    nameKey: 'veh.ship_ferry1',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1990,
    priceCt: 14_000_000,
    upkeepCtPerYear: 820_000,
    massKg: 800_000,
    lengthM: 62,
    tractiveN: 150_000,
    powerW: 1_400_000,
    maxSpeedMs: kmh(29),
    capacity: { [Cargo.CommuterPax]: 600 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_700,
    lifetimeYears: 28,
    co2PerKm: 24,
  },
  {
    id: 2041,
    nameKey: 'veh.ship_ferry2',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 1988,
    retireYear: 2040,
    priceCt: 25_000_000,
    upkeepCtPerYear: 1_240_000,
    massKg: 1_400_000,
    lengthM: 92,
    tractiveN: 230_000,
    powerW: 3_000_000,
    maxSpeedMs: kmh(42),
    capacity: { [Cargo.CommuterPax]: 1_100 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_100,
    lifetimeYears: 30,
    co2PerKm: 33,
  },
  {
    id: 2042,
    nameKey: 'veh.ship_ferry3',
    kind: VehicleKind.Ship,
    railRole: RailRole.None,
    introYear: 2025,
    retireYear: 2050,
    priceCt: 31_000_000,
    upkeepCtPerYear: 900_000,
    massKg: 1_300_000,
    lengthM: 90,
    tractiveN: 240_000,
    powerW: 3_200_000,
    maxSpeedMs: kmh(45),
    capacity: { [Cargo.CommuterPax]: 1_200 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 30,
    co2PerKm: 2,
  },
];

export const AIRCRAFT_SPECS: readonly VehicleSpec[] = [
  // ------------------------------------------------------- piston airliners
  {
    id: 3000,
    nameKey: 'veh.air_prop1',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1950,
    retireYear: 1968,
    priceCt: 21_000_000,
    upkeepCtPerYear: 2_100_000,
    massKg: 24_000,
    lengthM: 24,
    tractiveN: 42_000,
    powerW: 2_600_000,
    maxSpeedMs: kmh(430),
    capacity: { [Cargo.CommuterPax]: 120 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 7_800,
    lifetimeYears: 20,
    co2PerKm: 9.2,
  },
  {
    id: 3001,
    nameKey: 'veh.air_prop2',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1958,
    retireYear: 1982,
    priceCt: 29_000_000,
    upkeepCtPerYear: 2_450_000,
    massKg: 38_000,
    lengthM: 31,
    tractiveN: 58_000,
    powerW: 4_100_000,
    maxSpeedMs: kmh(520),
    capacity: { [Cargo.CommuterPax]: 200 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_100,
    lifetimeYears: 22,
    co2PerKm: 12.4,
  },
  // --------------------------------------------------------------- jets
  {
    id: 3010,
    nameKey: 'veh.air_jet1',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1962,
    retireYear: 1990,
    priceCt: 48_000_000,
    upkeepCtPerYear: 3_600_000,
    massKg: 62_000,
    lengthM: 41,
    tractiveN: 92_000,
    powerW: 9_800_000,
    maxSpeedMs: kmh(810),
    capacity: { [Cargo.CommuterPax]: 330 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_600,
    lifetimeYears: 24,
    co2PerKm: 21,
  },
  {
    id: 3011,
    nameKey: 'veh.air_jet2',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1978,
    retireYear: 2008,
    priceCt: 72_000_000,
    upkeepCtPerYear: 4_400_000,
    massKg: 88_000,
    lengthM: 49,
    tractiveN: 128_000,
    powerW: 14_500_000,
    maxSpeedMs: kmh(870),
    capacity: { [Cargo.CommuterPax]: 520 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_000,
    lifetimeYears: 26,
    co2PerKm: 28,
  },
  {
    id: 3012,
    nameKey: 'veh.air_jet3',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1996,
    retireYear: 2030,
    priceCt: 96_000_000,
    upkeepCtPerYear: 4_900_000,
    massKg: 112_000,
    lengthM: 56,
    tractiveN: 156_000,
    powerW: 19_000_000,
    maxSpeedMs: kmh(900),
    capacity: { [Cargo.CommuterPax]: 720 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_300,
    lifetimeYears: 28,
    co2PerKm: 33,
  },
  {
    id: 3013,
    nameKey: 'veh.air_jet4',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 2020,
    retireYear: 2050,
    priceCt: 118_000_000,
    upkeepCtPerYear: 4_200_000,
    massKg: 104_000,
    lengthM: 54,
    tractiveN: 160_000,
    powerW: 18_000_000,
    maxSpeedMs: kmh(910),
    capacity: { [Cargo.CommuterPax]: 780 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'hydrogen',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_500,
    lifetimeYears: 30,
    co2PerKm: 3.1,
  },
  // ------------------------------------------------------------ commuters
  {
    id: 3020,
    nameKey: 'veh.air_commuter1',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1966,
    retireYear: 1998,
    priceCt: 16_000_000,
    upkeepCtPerYear: 1_500_000,
    massKg: 14_000,
    lengthM: 19,
    tractiveN: 26_000,
    powerW: 1_800_000,
    maxSpeedMs: kmh(470),
    capacity: { [Cargo.CommuterPax]: 95 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_400,
    lifetimeYears: 22,
    co2PerKm: 5.8,
  },
  {
    id: 3021,
    nameKey: 'veh.air_commuter2',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1992,
    retireYear: 2035,
    priceCt: 27_000_000,
    upkeepCtPerYear: 1_900_000,
    massKg: 22_000,
    lengthM: 26,
    tractiveN: 38_000,
    powerW: 3_400_000,
    maxSpeedMs: kmh(620),
    capacity: { [Cargo.CommuterPax]: 185 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_100,
    lifetimeYears: 26,
    co2PerKm: 9.4,
  },
  {
    id: 3022,
    nameKey: 'veh.air_commuter3',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 2032,
    retireYear: 2050,
    priceCt: 34_000_000,
    upkeepCtPerYear: 1_400_000,
    massKg: 20_000,
    lengthM: 25,
    tractiveN: 40_000,
    powerW: 3_600_000,
    maxSpeedMs: kmh(640),
    capacity: { [Cargo.CommuterPax]: 200 },
    refittable: [Cargo.BusinessPax, Cargo.Mail],
    power: 'battery',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 9_400,
    lifetimeYears: 28,
    co2PerKm: 1.2,
  },
  // ------------------------------------------------------------ freighters
  {
    id: 3030,
    nameKey: 'veh.air_freight1',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1970,
    retireYear: 2005,
    priceCt: 64_000_000,
    upkeepCtPerYear: 4_100_000,
    massKg: 96_000,
    lengthM: 47,
    tractiveN: 120_000,
    powerW: 13_000_000,
    maxSpeedMs: kmh(780),
    capacity: { [Cargo.Goods]: 70 },
    refittable: [Cargo.Goods, Cargo.Mail, Cargo.Electronics, Cargo.Food],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 8_800,
    lifetimeYears: 26,
    co2PerKm: 26,
  },
  {
    id: 3031,
    nameKey: 'veh.air_freight2',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 2002,
    retireYear: 2050,
    priceCt: 104_000_000,
    upkeepCtPerYear: 5_200_000,
    massKg: 148_000,
    lengthM: 62,
    tractiveN: 180_000,
    powerW: 22_000_000,
    maxSpeedMs: kmh(880),
    capacity: { [Cargo.Goods]: 140 },
    refittable: [Cargo.Goods, Cargo.Mail, Cargo.Electronics, Cargo.Food, Cargo.Containers],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: true,
    reliability0: 9_200,
    lifetimeYears: 28,
    co2PerKm: 38,
  },
  {
    id: 3032,
    nameKey: 'veh.air_mail',
    kind: VehicleKind.Aircraft,
    railRole: RailRole.None,
    introYear: 1954,
    retireYear: 1988,
    priceCt: 18_000_000,
    upkeepCtPerYear: 1_700_000,
    massKg: 18_000,
    lengthM: 21,
    tractiveN: 30_000,
    powerW: 2_100_000,
    maxSpeedMs: kmh(450),
    capacity: { [Cargo.Mail]: 310 },
    refittable: [Cargo.Mail, Cargo.Goods],
    power: 'diesel',
    needsCatenary: false,
    hasCooling: false,
    reliability0: 8_000,
    lifetimeYears: 21,
    co2PerKm: 6.4,
  },
];
