import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * The repo-glob guard of E-14: no binary asset ever enters git. The Kenney
 * pipeline (M12 stage 0, D-160) downloads kits and bakes PNG atlases, and
 * BOTH live in gitignored directories - this test walks the actual git
 * index, so a stray `git add -f` of a model or an atlas page turns the
 * build red instead of quietly bloating the repository (Fehlerkatalog 31).
 */

const REPO_ROOT = fileURLToPath(new URL('../..', import.meta.url));

/**
 * Everything that is an image, a model, an archive, a font, a sound - or a
 * binary the GAME itself writes. The list errs towards breadth: a false
 * positive costs one allowlist line, a false negative costs the
 * regeneration-cost advantage for ever.
 *
 * `.ironsave` and `.ironreplay` joined the list in M16's correction bundle.
 * They had been missing since the corpus fixtures were committed, so the six
 * files this guard is most likely to grow a seventh of - zlib over MessagePack,
 * one per save version - were never actually being walked: the guard read as
 * green because it could not see them. They are legitimate and stay, but they
 * stay on the ALLOWLIST, where a reviewer sees them.
 */
const BINARY_EXTENSIONS =
  /\.(png|jpe?g|gif|webp|bmp|tiff?|ico|icns|glb|gltf|fbx|obj|blend|zip|gz|tgz|tar|7z|rar|ttf|otf|woff2?|eot|mp3|ogg|wav|flac|mp4|webm|bin|dat|exe|dll|so|dylib|wasm|ironsave|ironreplay)$/i;

/**
 * The two deliberate exceptions, each with the reason it earns its bytes.
 *
 * - The Tauri application icons: generated by `npm run icons` from
 *   tools/make-icons.mjs (reproducible from code, the 16.2 rule) but committed
 *   because the desktop bundler reads them from disk at build time.
 * - The migration corpus (D-130): one small played save per save version,
 *   which is the ONLY way to prove that a world written by an older build
 *   still loads. It cannot be regenerated from code by definition - the build
 *   that wrote it no longer exists - so it is history, not an asset. The
 *   manifest hash in tests/corpus/fixtures/manifest.json is what keeps the
 *   set honest, and `saveCorpus.spec.ts` reads every one of them.
 *
 * Nothing else earns a place here.
 */
const ALLOWED_PREFIXES = ['src-tauri/icons/', 'tests/corpus/fixtures/'];

function gitLines(...args: string[]): string[] {
  return execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8' })
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

describe('no binary asset in the git index (E-14 glob test)', () => {
  it('finds no tracked binary file outside the icon allowlist', () => {
    const tracked = gitLines('ls-files');
    expect(tracked.length).toBeGreaterThan(0);
    const violations = tracked.filter(
      (file) =>
        BINARY_EXTENSIONS.test(file) && !ALLOWED_PREFIXES.some((prefix) => file.startsWith(prefix)),
    );
    expect(violations).toEqual([]);
  });

  it('leaves no allowlist entry the glob does not actually reach', () => {
    // A prefix that excuses nothing is either dead or - the case this test was
    // written for - an extension the pattern never matched, so the files under
    // it were exempt by accident rather than by decision.
    const tracked = gitLines('ls-files');
    for (const prefix of ALLOWED_PREFIXES) {
      const covered = tracked.filter(
        (file) => file.startsWith(prefix) && BINARY_EXTENSIONS.test(file),
      );
      expect(
        covered.length,
        `allowlist prefix "${prefix}" excuses no tracked binary file`,
      ).toBeGreaterThan(0);
    }
  });

  /**
   * The audio half of the same clause, asserted on its own (SPEC2 M25).
   *
   * The Fertig-wenn asks for it by name - "ein Repo-Glob keine Audiodatei
   * findet" - and the general guard above would go green on a repository with
   * an mp3 in it the day somebody widened `ALLOWED_PREFIXES` for an unrelated
   * reason. This one has no allowlist at all, because there is no sound in
   * this game that is not synthesised at run time (`src/audio/soundscape.ts`
   * is the whole sound library) and there never may be one.
   */
  it('finds no audio file anywhere in the index, with no exception', () => {
    const audio = /\.(mp3|ogg|oga|opus|wav|flac|aac|m4a|aiff?|wma|mid|midi|mod|xm|it|s3m)$/i;
    const tracked = gitLines('ls-files');
    expect(tracked.length).toBeGreaterThan(0);
    expect(tracked.filter((file) => audio.test(file))).toEqual([]);
  });

  it('keeps the asset cache and the bake output ignored', () => {
    // check-ignore exits non-zero when a path is NOT ignored - both pipeline
    // directories must stay outside the index by construction, not by care.
    for (const path of ['assets-cache/probe.zip', 'public/assets-baked/atlas-z1-p0.png']) {
      expect(() =>
        execFileSync('git', ['check-ignore', '-q', path], { cwd: REPO_ROOT }),
      ).not.toThrow();
    }
  });
});
